BHWeb/Areas/Organization/Controllers/LocationTypeController.cs
using BH.DataAccess.Infrastructure.Interface.IRepository;
using BH.Models.OrganizationManagement;
using BH.Utility;
using BHWeb.Areas.Admin.Controllers;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BHWeb.Areas.Organization.Controllers;
[Area("Organization")]
[Authorize(Roles = SDRoles.Role_Admin + "," + SDRoles.Role_ShopAdmin)]
public class LocationTypeController : BaseController
{
    private readonly IUnitOfWork _unitOfWork;
    private ApplicationUser applicationUser;
    public LocationTypeController(IUnitOfWork unitOfWork)
    {
        _unitOfWork = unitOfWork;
        applicationUser = _unitOfWork.ApplicationUser.GetFirstOrDefault(u => u.Id == _userId);
    }

    public IActionResult Index()
    {
        if (applicationUser == null)
        {
            applicationUser = _unitOfWork.ApplicationUser.GetFirstOrDefault(u => u.Id == _userId);
        }
        IEnumerable<LocationType> objList = _unitOfWork.LocationType.GetAll().Where(x => x.ShopId == _unitOfWork.ApplicationUser.GetFirstOrDefault(u => u.Id == _userId).ShopId);
        return View(objList);
    }

    //GET
    public IActionResult Create()
    {
        return View();
    }

    //POST
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Create(LocationType obj)
    {
        if (ModelState.IsValid)
        {
            obj.CreatedBy = _userId;
            obj.CreatedDate = DateTime.Now;
            obj.ShopId = applicationUser.ShopId;
            obj.IsDisable = false;
            _unitOfWork.LocationType.Add(obj);
            _unitOfWork.Save();
            TempData["success"] = "LocationType created successfully";
            return RedirectToAction("Index");
        }
        return View(obj);
    }

    //GET
    public IActionResult Edit(int? id)
    {
        if (id == null || id == 0)
        {
            return NotFound();
        }
        var FromDbFirst = _unitOfWork.LocationType.GetFirstOrDefault(u => u.Id == id);

        if (FromDbFirst == null)
        {
            return NotFound();
        }

        return View(FromDbFirst);
    }

    //POST
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Edit(LocationType obj)
    {

        if (ModelState.IsValid)
        {
            obj.ModifiedBy = _userId;
            obj.ModifiedDate = DateTime.UtcNow;
            _unitOfWork.LocationType.Update(obj);
            _unitOfWork.Save();
            TempData["success"] = "LocationType updated successfully";
            return RedirectToAction("Index");
        }
        return View(obj);
    }

    public IActionResult Delete(int? id)
    {
        if (id == null || id == 0)
        {
            return NotFound();
        }
        var FromDbFirst = _unitOfWork.LocationType.GetFirstOrDefault(u => u.Id == id);

        if (FromDbFirst == null)
        {
            return NotFound();
        }

        return View(FromDbFirst);
    }

    //POST
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public IActionResult DeletePOST(int? id)
    {
        var obj = _unitOfWork.LocationType.GetFirstOrDefault(u => u.Id == id);
        if (obj == null)
        {
            return NotFound();
        }

        _unitOfWork.LocationType.Remove(obj);
        _unitOfWork.Save();
        TempData["success"] = "LocationType deleted successfully";
        return RedirectToAction("Index");

    }
}

BHWeb/Areas/Organization/Views/LocationType/Create.cshtml
@model LocationType

<form method="post">
	<div class="border p-3 mt-4">
		<div class="row pb-2">
			<h2 class="text-primary">Create LocationType</h2>
			<hr />
		</div>
		@*<div asp-validation-summary="All"></div>*@
		<div class="mb-3">
			<label asp-for="Name"></label>
			<input asp-for="Name" class="form-control" />
			<span asp-validation-for="Name" class="text-danger"></span>
		</div>
		
		<button type="submit" class="btn btn-primary" style="width:150px">Create</button>
		<a asp-controller="LocationType" asp-action="Index" class="btn btn-secondary" style="width:150px">
			Back to List
		</a>
	</div>
</form>

@section Scripts{
	@{
		<partial name="_ValidationScriptsPartial" />
	}
}

BHWeb/Areas/Organization/Views/LocationType/Delete.cshtml
@model LocationType

<form method="post" asp-action="Delete">
	<input asp-for="Id" hidden />
	<div class="border p-3 mt-4">
		<div class="row pb-2">
			<h2 class="text-primary">Delete LocationType</h2>
			<hr />
		</div>
		@*<div asp-validation-summary="All"></div>*@
		<div class="mb-3">
			<label asp-for="Name"></label>
			<input asp-for="Name" disabled class="form-control" />
		</div>
		
		<button type="submit" class="btn btn-danger" style="width:150px">Delete</button>
		<a asp-controller="LocationType" asp-action="Index" class="btn btn-secondary" style="width:150px">
			Back to List
		</a>
	</div>
</form>

@section Scripts{
	@{
		<partial name="_ValidationScriptsPartial" />
	}
}

BHWeb/Areas/Organization/Views/LocationType/Edit.cshtml
@model LocationType

<form method="post" asp-action="Edit">
	<input asp-for="CreatedBy" hidden />
	<input asp-for="ShopId" hidden />
	<div class="border p-3 mt-4">
		<div class="row pb-2">
			<h2 class="text-primary">Edit LocationType</h2>
			<hr />
		</div>
		@*<div asp-validation-summary="All"></div>*@
		<div class="mb-3">
			<label asp-for="Name"></label>
			<input asp-for="Name" class="form-control" />
			<span asp-validation-for="Name" class="text-danger"></span>
		</div>
		
		<div class="mb-3">
			<label asp-for="IsDisable" class="form-check-label">
				<input asp-for="IsDisable" class="form-control form-check-input" /> @Html.DisplayNameFor(model => model.IsDisable)
			</label>
			<span asp-validation-for="IsDisable" class="text-danger"></span>
		</div>
		
		<button type="submit" class="btn btn-primary" style="width:150px">Update</button>
		<a asp-controller="LocationType" asp-action="Index" class="btn btn-secondary" style="width:150px">
			Back to List
		</a>
	</div>
</form>

@section Scripts{
	@{
		<partial name="_ValidationScriptsPartial" />
	}
}

BHWeb/Areas/Organization/Views/LocationType/Index.cshtml
@model IEnumerable<LocationType>
@{
    ViewData["Title"] = "Index";
}


<div class="p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">LocationType List</h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="LocationType" asp-action="Create" class="btn btn-primary" autofocus>
                <i class="bi bi-plus-circle"></i> &nbsp; Create New LocationType
            </a>
        </div>
    </div>
    <br /><br />

    <table id="tblData" class="table table-bordered table-striped zero-configuration" style="width:100%">
        <thead>
            <tr>
                <th>@Html.DisplayNameFor(model => model.IsDisable)</th>
                <th>@Html.DisplayNameFor(model => model.Name)</th>
                <th>@Html.DisplayNameFor(model => model.CreatedBy)</th>
                <th>@Html.DisplayNameFor(model => model.CreatedDate)</th>
                <th>@Html.DisplayNameFor(model => model.ModifiedBy)</th>
                <th>@Html.DisplayNameFor(model => model.ModifiedDate)</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var obj in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(m => obj.IsDisable)
                    </td>
                    <td>
                        @Html.DisplayFor(m => obj.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(x => obj.ApplicationUser.FullName)
                    </td>
                    <td>
                        @Html.DisplayFor(x => obj.CreatedDate)
                    </td>
                    <td>
                        @Html.DisplayFor(x => obj.ModifyingUser.FullName)
                    </td>
                    <td>
                        @Html.DisplayFor(x => obj.ModifiedDate)
                    </td>
                    <td>
                        <div class="w-75 btn-group" role="group">
                            <a asp-controller="LocationType" asp-action="Edit" asp-route-id="@obj.Id"
                           class="btn btn-primary mx-2"> <i class="bi bi-pencil-square"></i> Edit</a>
                            <a asp-controller="LocationType" asp-action="Delete" asp-route-id="@obj.Id"
                           class="btn btn-danger mx-2"> <i class="bi bi-trash-fill"></i> Delete</a>
                        </div>
                    </td>
                </tr>
            }
        </tbody>

    </table>
</div>