BHWeb/Areas/Admin/Controllers/SuppliersController.cs
using BH.DataAccess.Infrastructure.Interface.IRepository;
using BH.Models.OrganizationManagement;
using BH.Models.ShopManagement;
using BH.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace BHWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SDRoles.Role_Admin + "," + SDRoles.Role_ShopAdmin)]
    public class SuppliersController : BaseController
    {
        private readonly IUnitOfWork _unitOfWork;
        private ApplicationUser applicationUser;
        public SuppliersController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
            applicationUser = _unitOfWork.ApplicationUser.GetFirstOrDefault(u => u.Id == _userId);
        }

        public IActionResult Index()
        {
            if (applicationUser == null)
            {
                applicationUser = _unitOfWork.ApplicationUser.GetFirstOrDefault(u => u.Id == _userId);
            }
            IEnumerable<Supplier> objList = _unitOfWork.Supplier.GetAll().Where(x => x.ShopId == applicationUser.ShopId && x.IsDisable != true && x.IsDeleted != true);
            return View(objList);
        }

        //GET
        public IActionResult Upsert(int? id)
        {
            Supplier obj = new();
            ViewData["PaymentMethodList"] = _unitOfWork.PaymentMethod.GetAll().Where(x => x.IsDisable != true && x.IsDeleted != true).Select(i => new SelectListItem { Text = i.Name, Value = i.Id.ToString() });
            if (id == null || id == 0)
            {
                return View(obj);
            }
            else
            {
                obj = _unitOfWork.Supplier.GetFirstOrDefault(u => u.Id == id);
                return View(obj);
            }
        }
        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(Supplier obj)
        {
            if (ModelState.IsValid)
            {
                if (obj.Id == 0)
                {
                    obj.CreatedBy = _userId;
                    obj.CreatedDate = DateTime.UtcNow;
                    obj.ShopId = applicationUser.ShopId;
                    obj.IsDisable = false;
                    _unitOfWork.Supplier.Add(obj);
                    TempData["success"] = "Supplier created successfully";
                }
                else
                {
                    obj.ModifiedBy = _userId;
                    obj.ModifiedDate = DateTime.UtcNow;
                    _unitOfWork.Supplier.Update(obj);
                    TempData["success"] = "Supplier updated successfully";
                }
                _unitOfWork.Save();

                return RedirectToAction("Index");
            }
            return View(obj);
        }

        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var FromDbFirst = _unitOfWork.Supplier.GetFirstOrDefault(u => u.Id == id);

            if (FromDbFirst == null)
            {
                return NotFound();
            }

            return View(FromDbFirst);
        }

        //POST
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePOST(int? id)
        {
            var obj = _unitOfWork.Supplier.GetFirstOrDefault(u => u.Id == id);
            if (obj == null)
            {
                return NotFound();
            }

            _unitOfWork.Supplier.Remove(obj);
            _unitOfWork.Save();
            TempData["success"] = "Supplier deleted successfully";
            return RedirectToAction("Index");
        }
    }
}

BHWeb/Areas/Admin/Views/Suppliers/Delete.cshtml
@model Supplier

<form method="post" asp-action="Delete">
	<input asp-for="Id" hidden />
	<div class="border p-3 mt-4">
		<div class="row pb-2">
			<h2 class="text-primary">Delete Supplier</h2>
			<hr />
		</div>
		@*<div asp-validation-summary="All"></div>*@
		<div class="mb-3">
			<label asp-for="Name"></label>
			<input asp-for="Name" disabled class="form-control" />
		</div>
		<div class="mb-3">
			<label asp-for="ContactPerson"></label>
			<input asp-for="ContactPerson" disabled class="form-control" />
		</div>
		<div class="mb-3">
			<label asp-for="ContactTitle"></label>
			<input asp-for="ContactTitle" disabled class="form-control" />
		</div>
		<div class="mb-3">
			<label asp-for="ContactPhone"></label>
			<input asp-for="ContactPhone" disabled class="form-control" />
		</div>
		<div class="mb-3">
			<label asp-for="LicenseNum"></label>
			<input asp-for="LicenseNum" disabled class="form-control" />
		</div>

		<button type="submit" class="btn btn-danger" style="width:150px">Delete</button>
		<a asp-controller="Suppliers" asp-action="Index" class="btn btn-secondary" style="width:150px">
			Back to List
		</a>
	</div>
</form>

@section Scripts{
	@{
		<partial name="_ValidationScriptsPartial" />
	}
}

BHWeb/Areas/Admin/Views/Suppliers/Index.cshtml
@model IEnumerable<Supplier>
@{
    ViewData["Title"] = "Supplier List";
}


<div class="p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Supplier List</h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="Suppliers" asp-action="Upsert" class="btn btn-primary" autofocus>
                <i class="bi bi-plus-circle"></i> &nbsp; Create New Supplier
            </a>
        </div>
    </div>
    <br /><br />

    <table id="tblData" class="table table-bordered table-striped zero-configuration" style="width:100%">
        <thead>
            <tr>
                <th></th>
                <th>@Html.DisplayNameFor(model => model.IsDisable)</th>
                <th>@Html.DisplayNameFor(model => model.Name)</th>
                <th>@Html.DisplayNameFor(model => model.ContactPerson)</th>
                <th>@Html.DisplayNameFor(model => model.LicenseNum)</th>
                <th>@Html.DisplayNameFor(model => model.ContactTitle)</th>
                <th>@Html.DisplayNameFor(model => model.ContactPhone)</th>
                <th>@Html.DisplayNameFor(model => model.City)</th>
                <th>@Html.DisplayNameFor(model => model.ContactEmail)</th>
                <th>@Html.DisplayNameFor(model => model.CreatedBy)</th>
                <th>@Html.DisplayNameFor(model => model.CreatedDate)</th>
                <th>@Html.DisplayNameFor(model => model.ModifiedBy)</th>
                <th>@Html.DisplayNameFor(model => model.ModifiedDate)</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var obj in Model)
            {
                <tr>
                    <td>
                        <div class="btn-group" role="group">
                            <a asp-controller="Suppliers" asp-action="Upsert" asp-route-id="@obj.Id"
                           class="btn btn-primary mx-2"> <i class="bi bi-pencil-square"></i> Edit</a>
                            <a asp-controller="Suppliers" asp-action="Delete" asp-route-id="@obj.Id"
                           class="btn btn-danger mx-2"> <i class="bi bi-trash-fill"></i> Delete</a>
                        </div>
                    </td>
                    <td>
                        @Html.DisplayFor(m => obj.IsDisable)
                    </td>
                    <td>
                        @Html.DisplayFor(m => obj.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(m => obj.ContactPerson)
                    </td>
                    <td>
                        @Html.DisplayFor(m => obj.LicenseNum)
                    </td>
                    <td>
                        @Html.DisplayFor(m => obj.ContactTitle)
                    </td>
                    <td>
                        @Html.DisplayFor(m => obj.ContactPhone)
                    </td>
                    <td>
                        @Html.DisplayFor(m => obj.City)
                    </td>
                    <td>
                        @Html.DisplayFor(m => obj.ContactEmail)
                    </td>
                    <td>
                        @Html.DisplayFor(x => obj.ApplicationUser.FullName)
                    </td>
                    <td>
                        @Html.DisplayFor(x => obj.CreatedDate)
                    </td>
                    <td>
                        @Html.DisplayFor(x => obj.ModifyingUser.FullName)
                    </td>
                    <td>
                        @Html.DisplayFor(x => obj.ModifiedDate)
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

BHWeb/Areas/Admin/Views/Suppliers/Upsert.cshtml
@model Supplier
@{
    ViewData["Title"] = Model.Id != 0 ? "Update" : "Create";
}
<form method="post" asp-area="Admin" asp-controller="Suppliers" asp-action="Upsert">
    <input asp-for="Id" hidden />
    <input asp-for="CreatedBy" hidden />
    <input asp-for="CreatedDate" hidden />
    <input asp-for="ShopId" hidden />
    
    <div class="row">
        <div class="col-12">
            <div class="border p-3 mt-4 row">
                <div class="col-12 pb-2">
                    <h2 class="text-primary">@(Model.Id != 0 ? "Update" : "Create")  Supplier</h2>
                    <hr />
                </div>
                <div class="col-4">
                    <div class="mb-3">
                        <label asp-for="Name"></label>
                        <input asp-for="Name" class="form-control" autofocus />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="mb-3">
                        <label asp-for="ContactPerson"></label>
                        <input asp-for="ContactPerson" class="form-control" />
                        <span asp-validation-for="ContactPerson" class="text-danger"></span>
                    </div>
                    <div class="mb-3">
                        <label asp-for="ContactTitle"></label>
                        <input asp-for="ContactTitle" class="form-control" />
                        <span asp-validation-for="ContactTitle" class="text-danger"></span>
                    </div>
                    <div class="mb-3">
                        <label asp-for="ContactEmail"></label>
                        <input asp-for="ContactEmail" class="form-control" />
                        <span asp-validation-for="ContactEmail" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-4">
                    <div class="mb-3">
                        <label asp-for="ContactPhone"></label>
                        <input asp-for="ContactPhone" class="form-control" />
                        <span asp-validation-for="ContactPhone" class="text-danger"></span>
                    </div>
                    <div class="mb-3">
                        <label asp-for="City"></label>
                        <input asp-for="City" class="form-control" />
                        <span asp-validation-for="City" class="text-danger"></span>
                    </div>
                    <div class="mb-3">
                        <label asp-for="State"></label>
                        <input asp-for="State" class="form-control" />
                        <span asp-validation-for="State" class="text-danger"></span>
                    </div>
                    <div class="mb-3">
                        <label asp-for="Country"></label>
                        <input asp-for="Country" class="form-control" />
                        <span asp-validation-for="Country" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-4">
                    <div class="mb-3">
                        <label asp-for="Address"></label>
                        <input asp-for="Address" class="form-control" />
                        <span asp-validation-for="Address" class="text-danger"></span>
                    </div>
                    <div class="mb-3">
                        <label asp-for="LicenseNum"></label>
                        <input asp-for="LicenseNum" class="form-control" />
                        <span asp-validation-for="LicenseNum" class="text-danger"></span>
                    </div>
                    <div class="mb-3">
                        <label asp-for="PaymentTermsDays"></label>
                        <input asp-for="PaymentTermsDays" class="form-control" />
                        <span asp-validation-for="PaymentTermsDays" class="text-danger"></span>
                    </div>
                    <div class="mb-3">
                        <label asp-for="PaymentMethodId"></label>
                        <select asp-for="PaymentMethodId" asp-items="@ViewBag.PaymentMethodList" class="form-control">
                            <option selected disabled>- Select -</option>
                        </select>
                        <span asp-validation-for="PaymentMethodId" class="text-danger"></span>
                    </div>
                </div>

                @if (Model.Id != 0)
                {
                    <div class="mb-3">
                        <label asp-for="IsDisable" class="form-check-label">
                            <input asp-for="IsDisable" class="form-control form-check-input" />
                            @Html.DisplayNameFor(model => model.IsDisable)
                        </label>
                        <span asp-validation-for="IsDisable" class="text-danger"></span>
                    </div>
                }

                <div class="col-12">
                    @if (Model.Id != 0)
                    {
                        <button type="submit" class="btn btn-primary" style="width:150px">Update</button>
                    }
                    else
                    {
                        <button type="submit" class="btn btn-primary" style="width:150px">Create</button>
                    }
                    <a asp-controller="Suppliers" asp-action="Index" class="btn btn-secondary" style="width:150px">
                        Back to List
                    </a>
                </div>
            </div>
        </div>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}