BHWeb/Areas/Accounts/Controllers/ExpenseTypeController.cs
using BH.DataAccess.Infrastructure.Interface.IRepository;
using BH.Models.AccountManagement;
using BH.Models.OrganizationManagement;
using BH.Utility;
using BHWeb.Areas.Admin.Controllers;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BHWeb.Areas.AccountManagement.Controllers
{
    [Area("Accounts")]
    [Authorize(Roles = SDRoles.Role_Admin + "," + SDRoles.Role_ShopAdmin + "," + SDRoles.Role_ShopUser)]
    public class ExpenseTypeController : BaseController
    {
        private readonly IUnitOfWork _unitOfWork;
        private ApplicationUser applicationUser;
        public ExpenseTypeController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
            applicationUser = _unitOfWork.ApplicationUser.GetFirstOrDefault(u => u.Id == _userId);
        }

        public IActionResult Index()
        {
            if (applicationUser == null)
            {
                applicationUser = _unitOfWork.ApplicationUser.GetFirstOrDefault(u => u.Id == _userId);
            }
            IEnumerable<ExpenseType> objList = _unitOfWork.ExpenseType.GetAll(x => x.ShopId == applicationUser.ShopId && x.IsDisable != true && x.IsDeleted != true);
            return View(objList);
        }

        //GET
        public IActionResult Upsert(int? id)
        {
            ExpenseType obj = new();
            if (id == null || id == 0)
            {
                return View(obj);
            }
            else
            {
                obj = _unitOfWork.ExpenseType.GetFirstOrDefault(u => u.Id == id);
                return View(obj);
            }
        }
        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(ExpenseType obj)
        {
            if (ModelState.IsValid)
            {
                if (obj.Id == 0)
                {
                    obj.CreatedBy = _userId;
                    obj.CreatedDate = DateTime.UtcNow;
                    obj.ShopId = applicationUser.ShopId;
                    obj.IsDisable = false;
                    _unitOfWork.ExpenseType.Add(obj);
                    TempData["success"] = "Expense type added successfully";
                }
                else
                {
                    obj.ModifiedBy = _userId;
                    obj.ModifiedDate = DateTime.UtcNow;
                    _unitOfWork.ExpenseType.Update(obj);
                    TempData["success"] = "Expense type updated successfully";
                }
                _unitOfWork.Save();

                return RedirectToAction("Index");
            }
            return View(obj);
        }

        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var FromDbFirst = _unitOfWork.ExpenseType.GetFirstOrDefault(u => u.Id == id);

            if (FromDbFirst == null)
            {
                return NotFound();
            }

            return View(FromDbFirst);
        }

        //POST
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePOST(int? id)
        {
            var obj = _unitOfWork.ExpenseType.GetFirstOrDefault(u => u.Id == id);
            if (obj == null)
            {
                return NotFound();
            }

            _unitOfWork.ExpenseType.Remove(obj);
            _unitOfWork.Save();
            TempData["success"] = "Expense Type deleted successfully";
            return RedirectToAction("Index");
        }
    }
}

BHWeb/Areas/Accounts/Views/ExpenseType/Delete.cshtml
@model ExpenseType

<form method="post" asp-action="Delete">
	<input asp-for="Id" hidden />
	<div class="border p-3 mt-4">
		<div class="row pb-2">
			<h2 class="text-primary">Delete Expense Type</h2>
			<hr />
		</div>
		@*<div asp-validation-summary="All"></div>*@
		<div class="mb-3">
			<label asp-for="Name"></label>
			<input asp-for="Name" disabled class="form-control" />
		</div>

		<button type="submit" class="btn btn-danger" style="width:150px">Delete</button>
		<a asp-controller="ExpenseType" asp-action="Index" class="btn btn-secondary" style="width:150px">
			Back to List
		</a>
	</div>
</form>

@section Scripts{
	@{
		<partial name="_ValidationScriptsPartial" />
	}
}

BHWeb/Areas/Accounts/Views/ExpenseType/Index.cshtml
@model IEnumerable<ExpenseType>
@{
    ViewData["Title"] = "Expense Type";
}


<div class="p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Expense Type</h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="ExpenseType" asp-action="Upsert" class="btn btn-primary" autofocus>
                <i class="bi bi-plus-circle"></i> &nbsp; Add Expense Type
            </a>
        </div>
    </div>
    <br /><br />

    <table id="tblData" class="table table-bordered table-striped zero-configuration" style="width:100%">
        <thead>
            <tr>
                <th></th>
                <th>@Html.DisplayNameFor(model => model.Name)</th>
                <th>@Html.DisplayNameFor(model => model.CreatedBy)</th>
                <th>@Html.DisplayNameFor(model => model.CreatedDate)</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var obj in Model)
            {
                <tr>
                    <td>
                        <div class="w-75 btn-group" role="group">
                            <a asp-controller="ExpenseType" asp-action="Upsert" asp-route-id="@obj.Id"
                               class="btn btn-primary mx-2"> <i class="bi bi-pencil-square"></i> Edit</a>
                            <a asp-controller="ExpenseType" asp-action="Delete" asp-route-id="@obj.Id"
                               class="btn btn-danger mx-2"> <i class="bi bi-trash-fill"></i> Delete</a>
                        </div>
                    </td>
                    <td>
                        @Html.DisplayFor(m => obj.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(x => obj.ApplicationUser.FullName)
                    </td>
                    <td>
                        @Html.DisplayFor(x => obj.CreatedDate)
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

BHWeb/Areas/Accounts/Views/ExpenseType/Upsert.cshtml
@model ExpenseType

<form method="post" asp-area="Accounts" asp-controller="ExpenseType" asp-action="Upsert">
    <input asp-for="Id" hidden />
    <input asp-for="CreatedBy" hidden />
    <input asp-for="ShopId" hidden />
    
    <div class="row">
        <div class="col-12">
            <div class="border p-3 mt-4 row">
                <div class="col-12 pb-2">
                    <h2 class="text-primary">@(Model.Id != 0 ? "Update" : "Create")  Expense Type</h2>
                    <hr />
                </div>
                <div class="col-4">
                    <div class="mb-3">
                        <label asp-for="Name"></label>
                        <input asp-for="Name" class="form-control" autofocus />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                </div>

                @if (Model.Id != 0)
                {
                    <div class="mb-3">
                        <label asp-for="IsDisable" class="form-check-label">
                            <input asp-for="IsDisable" class="form-control form-check-input" />
                            @Html.DisplayNameFor(model => model.IsDisable)
                        </label>
                        <span asp-validation-for="IsDisable" class="text-danger"></span>
                    </div>
                }

                <div class="col-12">
                    @if (Model.Id != 0)
                    {
                        <button type="submit" class="btn btn-primary" style="width:150px">Update</button>
                    }
                    else
                    {
                        <button type="submit" class="btn btn-primary" style="width:150px">Create</button>
                    }
                    <a asp-controller="ExpenseType" asp-action="Index" class="btn btn-secondary" style="width:150px">
                        Back to List
                    </a>
                </div>
            </div>
        </div>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}