BHWeb/Areas/Customer/Controllers/ShopCustomerController.cs
using BH.DataAccess.Infrastructure.Interface.IRepository;
using BH.Models.CustomerManagement;
using BH.Models.OrganizationManagement;
using BH.Models.ViewModels;
using BH.Utility;
using BHWeb.Areas.Admin.Controllers;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Hosting;

namespace BHWeb.Areas.Customer.Controllers
{
    [Area("Customer")]
    [Authorize(Roles = SDRoles.Role_Admin + "," + SDRoles.Role_ShopAdmin)]
    public class ShopCustomerController : BaseController
    {
        private readonly IUnitOfWork _unitOfWork;
        private ApplicationUser applicationUser;
        public ShopCustomerController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
            applicationUser = _unitOfWork.ApplicationUser.GetFirstOrDefault(u => u.Id == _userId);
        }
        public IActionResult Index()
        {
            if (applicationUser == null)
            {
                applicationUser = _unitOfWork.ApplicationUser.GetFirstOrDefault(u => u.Id == _userId);
            }
            IEnumerable<ShopCustomer> objList = _unitOfWork.ShopCustomer.GetAll(includeProperties: "CustomerRoute").Where(x => x.ShopId == applicationUser.ShopId);
            return View(objList);
        }


        public IActionResult CustomerOfRouteList(int routeId)
        {
            try
            {
                applicationUser ??= _unitOfWork.ApplicationUser.GetFirstOrDefault(u => u.Id == _userId);
                var customers = _unitOfWork.ShopCustomer.GetAll(includeProperties: "CustomerRoute")
                    .Where(x => x.ShopId == applicationUser.ShopId && x.CustomerRouteId == routeId);
                var AccountReceivables = _unitOfWork.AccountReceivable.GetAll(x => x.ShopId == applicationUser.ShopId &&
                                                                                   x.ShopCustomer != null && // Ensure ShopCustomer is not null
                                                                                   x.ShopCustomer.CustomerRouteId == routeId).OrderByDescending(ar => ar.ReceivedDate);
                var StockTransfers = _unitOfWork.StockTransfer.GetAll(x => x.ShopId == applicationUser.ShopId &&
                                                                           x.ShopCustomer != null &&
                                                                           x.ShopCustomer.CustomerRouteId == routeId).OrderByDescending(st => st.CreatedDate);

                var viewModel = customers.Select(c => new ShopCustomerVM
                {
                    Customer = c,
                    LastReceivedDate = AccountReceivables.FirstOrDefault(st => st.ShopCustomerId == c.Id)?.ReceivedDate,
                    LastRecovery = AccountReceivables.FirstOrDefault(st => st.ShopCustomerId == c.Id)?.ReceivedAmount,
                    LastStockTransferDate = StockTransfers.FirstOrDefault(st => st.ShopCustomerId == c.Id)?.CreatedDate,

                    largerDate = (AccountReceivables.FirstOrDefault(st => st.ShopCustomerId == c.Id)?.ReceivedDate == null) ? StockTransfers.FirstOrDefault(st => st.ShopCustomerId == c.Id)?.CreatedDate :
                                    (StockTransfers.FirstOrDefault(st => st.ShopCustomerId == c.Id)?.CreatedDate == null) ? AccountReceivables.FirstOrDefault(st => st.ShopCustomerId == c.Id)?.ReceivedDate :
                                    (AccountReceivables.FirstOrDefault(st => st.ShopCustomerId == c.Id)?.ReceivedDate
                                > StockTransfers.FirstOrDefault(st => st.ShopCustomerId == c.Id)?.CreatedDate) ?
                                AccountReceivables.FirstOrDefault(st => st.ShopCustomerId == c.Id)?.ReceivedDate :
                                StockTransfers.FirstOrDefault(st => st.ShopCustomerId == c.Id)?.CreatedDate

                }).ToList();

                return View(viewModel);
            }
            catch (Exception ex)
            {
                // Log error
                return StatusCode(500, $"Internal server error: {ex.Message}");
            }
        }



        //GET
        public IActionResult Upsert(int? id, string? addPOS)
        {
            ViewBag.CustomerRoute = _unitOfWork.CustomerRoute.GetAll().Where(x => x.ShopId == applicationUser.ShopId).Select(i => new SelectListItem { Text = i.RouteName, Value = i.Id.ToString() });
            ShopCustomer shopCoustomer = new();
            if (addPOS != null)
            {
                shopCoustomer.CreateFromPOS = addPOS;
            }

            if (id == null || id == 0)
            {
                return View(shopCoustomer);
            }
            else
            {
                shopCoustomer = _unitOfWork.ShopCustomer.GetFirstOrDefault(u => u.Id == id);
                return View(shopCoustomer);
            }
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(ShopCustomer obj)
        {
            if (ModelState.IsValid)
            {
                if (obj.Id == 0)
                {
                    obj.CreatedBy = _userId;
                    obj.CreatedDate = DateTime.Now;
                    obj.CustomerCode = _unitOfWork.ShopCustomer.GenerateCustomerCode();
                    obj.ShopId = applicationUser.ShopId;
                    _unitOfWork.ShopCustomer.Add(obj);
                    TempData["success"] = "Customer Shop created successfully";
                }
                else
                {
                    obj.ModifiedBy = _userId;
                    obj.ModifiedDate = DateTime.Now;
                    _unitOfWork.ShopCustomer.Update(obj);
                    TempData["success"] = "Customer Shop updated successfully";
                }
                _unitOfWork.Save();
                if (obj.CreateFromPOS != null)
                {
                    return RedirectToAction(nameof(Index), "POS", new { area = "Customer" });
                }
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        [HttpGet]
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var FromDbFirst = _unitOfWork.ShopCustomer.GetFirstOrDefault(u => u.Id == id);

            if (FromDbFirst == null)
            {
                return NotFound();
            }

            return View(FromDbFirst);
        }

        //POST
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePOST(int? id)
        {
            var obj = _unitOfWork.ShopCustomer.GetFirstOrDefault(u => u.Id == id);
            if (obj == null)
            {
                return NotFound();
            }

            _unitOfWork.ShopCustomer.Remove(obj);
            _unitOfWork.Save();
            TempData["success"] = "Customer Shop deleted successfully";
            return RedirectToAction("Index");

        }
    }
}

BHWeb/Areas/Customer/Views/ShopCustomer/CustomerOfRouteList.cshtml
@model IEnumerable<ShopCustomerVM>

@{
    ViewData["Title"] = "Route Customer List";
    Layout = "~/Views/Shared/_LayoutNoNAV.cshtml";
    int srno = 0;
    double total = 0;
    var BGColor = "";
}

<div class="ignorForPrint">
    <div style="margin-top: 1rem !important; padding-bottom: 0rem !important;">
        <div class="row">
            <div class="col-3 d-flex justify-content-between">
                <button id="print" autofocus class="btn btn-primary col-4">Print</button>
                <a asp-area="Customer" asp-controller="CustomerRoute" asp-action="Index"
                   class="btn btn-success mx-2"> <i class="bi bi-bootstrap-reboot"> Back to Route List</i></a>
            </div>
        </div>
    </div>
</div>
<div class="mt-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">@Model.FirstOrDefault().Customer.CustomerRoute.RouteName Customer List</h2>
        </div>
    </div>
    <br /><br />
    <table id="tblData" class="table table-bordered table-striped" style="width:100%; margin:0px; padding:0px">
        <thead>
            <tr>
                <th>Sr #</th>
                <th>@Html.DisplayNameFor(model => model.Customer.CustomerName)</th>
                <th>@Html.DisplayNameFor(model => model.Customer.CustomerPhone)</th>
                <th>@Html.DisplayNameFor(model => model.Customer.CustomerAddress)</th>
                <th>@Html.DisplayNameFor(model => model.LastReceivedDate)</th>
                <th>@Html.DisplayNameFor(model => model.LastStockTransferDate)</th>
                <th>Last Visit</th>
                <th>@Html.DisplayNameFor(model => model.Customer.Balance)</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var obj in Model)
            {
                srno++;
                if (obj.Customer.Balance != null)
                {
                    total += (double)obj.Customer.Balance;
                }
                DateTime currentDate = DateTime.Now.Date;
                DateTime? largerDate = obj.largerDate;
                TimeSpan? timeSpan = currentDate.Subtract(largerDate ?? DateTime.MinValue);

                // Calculate the total number of days
                int totalDays = (int)(timeSpan?.TotalDays ?? 0);
                if(totalDays > 7) BGColor = "bg-danger text-light"; else BGColor = "";
                
                // To get months and years, we'll use a more precise method to handle different month lengths
                int years = currentDate.Year - (largerDate ?? DateTime.MinValue).Year;
                int months = currentDate.Month - (largerDate?.Month ?? 0);

                // Adjust months and years if the current month is earlier than the month of the larger date
                if (months < 0)
                {
                    years--;
                    months += 12;
                }

                // Finally, calculate days by subtracting the day of the month
                int days = currentDate.Day - (largerDate?.Day ?? 0);
                if (days < 0)
                {
                    months--;
                    DateTime previousMonth = currentDate.AddMonths(-1);
                    days += DateTime.DaysInMonth(previousMonth.Year, previousMonth.Month);
                }
                <tr>
                    <td>
                        @srno
                    </td>
                    <td>

                        @Html.DisplayFor(m => obj.Customer.CustomerCode) -
                        @Html.DisplayFor(m => obj.Customer.CustomerName)
                    </td>
                    <td>
                        @Html.DisplayFor(m => obj.Customer.CustomerPhone)
                    </td>
                    <td>
                        @Html.DisplayFor(m => obj.Customer.CustomerAddress)
                    </td>
                    <td>
                        @Html.DisplayFor(m => obj.LastReceivedDate) -
                        @if (obj.LastReceivedDate != null)
                        {
                            @Html.DisplayFor(m => obj.LastRecovery)
                        }
                    </td>
                    <td>
                        @Html.DisplayFor(m => obj.LastStockTransferDate)
                    </td>
                    <td class="@BGColor">
                        @years - @months - @days
                    </td>
                    <td align="right">
                        @Html.DisplayFor(m => obj.Customer.Balance)
                    </td>
                </tr>
                total = Math.Round((double)total, 2);
            }
        </tbody>
        <tfoot>
            <tr align="right">
                <th class="w-20" colspan="7">Total</th>
                <th class="w-20">@total.ToString("#.##")</th>
            </tr>
        </tfoot>
    </table>


</div>

@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
    <script>
        $(document).ready(function() {
            $("#print").click(function() {
                $(".ignorForPrint").hide();
                window.print();
                $(".ignorForPrint").show();
            });
        });
    </script>
}

BHWeb/Areas/Customer/Views/ShopCustomer/Delete.cshtml
@model ShopCustomer

<form method="post" asp-action="Delete">
	<input asp-for="Id" hidden />
	<div class="border p-3 mt-4">
		<div class="row pb-2">
			<h2 class="text-primary">Delete Customer</h2>
			<hr />
		</div>
		<div class="mb-3">
			<label asp-for="CustomerName"></label>
			<input asp-for="CustomerName" disabled class="form-control" />
		</div>
		
		<button type="submit" class="btn btn-danger" style="width:150px">Delete</button>
		<a asp-controller="ShopCustomer" asp-action="Index" class="btn btn-secondary" style="width:150px">
			Back to List
		</a>
	</div>
</form>

@section Scripts{
	@{
		<partial name="_ValidationScriptsPartial" />
	}
}

BHWeb/Areas/Customer/Views/ShopCustomer/Index.cshtml
@model IEnumerable<ShopCustomer>
@{
    ViewData["Title"] = "Customer Index";
    int sr = 0;
}


<div class="p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Customer List</h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="ShopCustomer" asp-action="Upsert" class="btn btn-primary" autofocus>
                <i class="bi bi-plus-circle"></i> &nbsp; Create New Customer
            </a>
        </div>
    </div>
    <br /><br />

    <table id="tblData" class="table table-bordered table-striped zero-configuration" style="width:100%">
        <thead>
            <tr>
                <th>Sr#</th>
                <th>@Html.DisplayNameFor(model => model.CustomerName)</th>
                <th>@Html.DisplayNameFor(model => model.Balance)</th>
                <th>@Html.DisplayNameFor(model => model.CustomerPhone)</th>
                <th>@Html.DisplayNameFor(model => model.CustomerRouteId)</th>
                <th>@Html.DisplayNameFor(model => model.CustomerCity)</th>
                <th>@Html.DisplayNameFor(model => model.CustomerAddress)</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var obj in Model)
            {
                sr++;
                <tr>
                    <td>
                        @sr
                    </td>
                    <td>
                        @Html.DisplayFor(m => obj.IsDisable) @Html.DisplayFor(m => obj.CustomerCode) - @Html.DisplayFor(m => obj.CustomerName)
                    </td>
                    <td>
                        @Html.DisplayFor(m => obj.Balance)
                    </td>
                    <td>
                        @Html.DisplayFor(m => obj.CustomerPhone)
                    </td>
                    <td>
                        @Html.DisplayFor(m => obj.CustomerRoute.RouteName)
                    </td>
                    <td>
                        @Html.DisplayFor(m => obj.CustomerCity)
                    </td>
                    <td>
                        @Html.DisplayFor(m => obj.CustomerAddress)
                    </td>
                    <td class="w-100 btn-group">
                        
                            <a asp-controller="ShopCustomer" asp-action="Upsert" asp-route-id="@obj.Id"
                               class="btn btn-primary mx-2"> <i class="bi bi-pencil-square"></i></a>
                            <a asp-controller="ShopCustomer" asp-action="Delete" asp-route-id="@obj.Id"
                               class="btn btn-danger mx-2"> <i class="bi bi-trash-fill"></i></a>
                        <a asp-area="Accounts" asp-controller="AccountReceivable" asp-action="CustomerSalesDetail" asp-route-CustomerId="@obj.Id"
                               class="btn btn-secondary mx-2"><i class="bi bi-eye-fill"> Sale</i></a>
                       
                    </td>
                </tr>
            }
        </tbody>

    </table>
</div>

BHWeb/Areas/Customer/Views/ShopCustomer/Upsert.cshtml
@model ShopCustomer

<form method="post" asp-area="Customer" asp-controller="ShopCustomer" asp-action="Upsert">
    <input asp-for="Id" hidden />
    <input asp-for="CreatedBy" hidden />
    <input asp-for="CreatedDate" hidden />
    <input asp-for="CustomerCode" hidden />
    <input asp-for="ShopId" hidden />
    <input asp-for="CreateFromPOS" hidden />

    <div class="row">
        <div class="col-12">
            <div class="border p-3 mt-4 row">
                <div class="col-12 pb-2">
                    <h2 class="text-primary">@(Model.Id != 0 ? "Update" : "Create")  Customer</h2>
                    <hr />
                </div>
                <div class="form-floating mb-3 col-4">
                    <input asp-for="CustomerName" class="form-control border-1 shadow" autofocus/>
                    <label asp-for="CustomerName"  class="ms-2 text-muted"></label>
                    <span asp-validation-for="CustomerName" class="text-danger"></span>
                </div>
                <div class="form-floating mb-3 col-4">
                    <select asp-for="CustomerRouteId" asp-items="@ViewBag.CustomerRoute" class="form-select border-1 shadow">
                        <option disabled selected>--Select--</option>
                    </select>
                    <label asp-for="CustomerRouteId"  class="ms-2 text-muted"></label>
                    <span asp-validation-for="CustomerRouteId" class="text-danger"></span>
                </div>
                <div class="form-floating mb-3 col-4">
                    <input asp-for="CustomerPhone" class="form-control border-1 shadow" />
                    <label asp-for="CustomerPhone"  class="ms-2 text-muted"></label>
                    <span asp-validation-for="CustomerPhone" class="text-danger"></span>
                </div>
                <div class="form-floating mb-3 col-4">
                    <input asp-for="CustomerAddress" class="form-control border-1 shadow" />
                    <label asp-for="CustomerAddress"  class="ms-2 text-muted"></label>
                    <span asp-validation-for="CustomerAddress" class="text-danger"></span>
                </div>
                <div class="form-floating mb-3 col-4">
                    <input asp-for="CustomerCity" class="form-control border-1 shadow" />
                    <label asp-for="CustomerCity"  class="ms-2 text-muted"></label>
                    <span asp-validation-for="CustomerCity" class="text-danger"></span>
                </div>
                <div class="form-floating mb-3 col-4">
                    <input asp-for="PaymentTermsDays" class="form-control border-1 shadow" />
                    <label asp-for="PaymentTermsDays"  class="ms-2 text-muted"></label>
                    <span asp-validation-for="PaymentTermsDays" class="text-danger"></span>
                </div>
                <div class="form-floating mb-3 col-4">
                    <input asp-for="CustomerCode" readonly class="form-control border-1 shadow" autofocus />
                    <label asp-for="CustomerCode" class="ms-2 text-muted"></label>
                    <span asp-validation-for="CustomerCode" class="text-danger"></span>
                </div>
                <div class="form-floating mb-3 col-4">
                    <input asp-for="Balance" readonly class="form-control border-1 shadow" />
                    <label asp-for="Balance"  class="ms-2 text-muted"></label>
                    <span asp-validation-for="Balance" class="text-danger"></span>
                </div>
                @if (Model.Id != 0)
                {
                    <div class="mb-3">
                        <label asp-for="IsDisable" class="form-check-label">
                            <input asp-for="IsDisable" class="form-control form-check-input" /> @Html.DisplayNameFor(model => model.IsDisable)
                        </label>
                        <span asp-validation-for="IsDisable" class="text-danger"></span>
                    </div>
                }

                <div class="col-12">
                    @if (Model.Id != 0)
                    {
                        <button type="submit" class="btn btn-primary" style="width:150px">Update</button>
                    }
                    else
                    {
                        <button type="submit" onclick="return ValidateInput()" class="btn btn-primary" style="width:150px">Create</button>
                    }
                    <a asp-controller="ShopCustomer" asp-action="Index" class="btn btn-secondary" style="width:150px">
                        Back to List
                    </a>
                </div>
            </div>
        </div>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}